/**
 * Canonical inventory of every Postgres RPC the application invokes.
 *
 * WHY THIS EXISTS. `anon-secdef-allowlist.ts` pins the four functions `anon`
 * may reach. Nothing pinned the opposite side: which RPCs must stay reachable
 * by `authenticated`. That gap allowed 22 SECURITY DEFINER RPCs to ship with
 * NO grant statement anywhere in the migration chain � they worked only
 * because an environment default happened to grant EXECUTE. Once the
 * 20260722160000 closure revokes PUBLIC, any such function would break in a
 * production-baseline database. This list is the regression pin.
 *
 * SOURCE. Extracted from every `.rpc("...")` call site under `apps/web`,
 * including the three closed string-literal unions that build the name
 * dynamically (worker invitations and the two engagement-link helpers).
 * `apps/web/lib/guards/secdef-local-reset-reproducibility.test.ts` asserts
 * every entry has an explicit `authenticated` EXECUTE grant in the migrations.
 *
 * MAINTENANCE. Adding a new `.rpc(...)` call site means adding the name here
 * AND granting EXECUTE to `authenticated` in the migration that creates it.
 * Note `apps/web/lib/supabase/types.ts` is NOT a usable source � it is stale
 * (58 live RPCs are missing from it), which is why call sites use `asAny`.
 */
export const CANONICAL_APP_RPCS = [
  "accept_agency_client_connection_v1",
  "accept_agency_worker_invitation",
  "accept_company_worker_invitation",
  "accept_invitation_by_id_v1",
  "accept_invitation_v1",
  "acknowledge_asset_assignment_v1",
  "acknowledge_demand_interest",
  "add_defect_correction_v1",
  "add_project_handover_entry_v1",
  "add_project_stage_v1",
  "add_role",
  "admin_list_worker_privacy_states",
  "admin_privacy_readiness_counts",
  "admin_set_company_verification",
  "admin_set_market_rate_average",
  "admin_set_worker_document_verification",
  "agency_pool_docs_readiness",
  "agency_worker_engagement_links",
  "apply_learning_auto_confirmation",
  "assign_agency_worker_role",
  "assign_company_worker_role",
  "assign_worker_to_project",
  "batch_review_exceptions",
  "cancel_worker_absence_v1",
  "close_stale_learning_review_items",
  "company_worker_engagement_links",
  "complete_onboarding",
  "confirm_worker_card",
  "contact_demand_owner_v1",
  "conversation_counterpart_identities",
  "conversation_source_context",
  "create_agency_client_connection_v1",
  "create_asset_v1",
  "create_contract_v1",
  "create_finance_record_v1",
  "create_follow_up_task_v1",
  "create_invitation_v1",
  "create_journal_entry_full",
  "create_marketplace_listing_v1",
  "create_proposal_v1",
  "create_work_task_v1",
  "current_profile_discoverability_consent",
  "decline_agency_client_connection_v1",
  "decline_invitation_v1",
  "delete_contract_v1",
  "delete_defect_v1",
  "delete_marketplace_listing_v1",
  "delete_project_budget_v1",
  "delete_project_stage_v1",
  "delete_proposal_v1",
  "disconnect_external_profile_v1",
  "end_worker_project_assignment",
  "get_invitation_preview_v1",
  "get_public_business_listings_v1",
  "get_public_business_profile_v1",
  "get_public_business_services_v1",
  "get_team_capability_summary_v1",
  "grant_employer_data_disclosure",
  "grant_profile_discoverability_consent",
  "has_employer_data_disclosure",
  "invite_agency_worker",
  "invite_company_worker",
  "issue_asset_v1",
  "list_agency_offer_progress_v1",
  "list_agency_offered_candidates_for_request_v1",
  "list_agency_offered_candidates_for_request_v2",
  "list_booking_engagement_workers_v1",
  "list_invitations_for_me_v1",
  "list_my_contact_disclosure_requests_v1",
  "list_my_team_enquiries_v1",
  "list_open_demand_for_agencies",
  "list_open_demand_for_workers",
  "list_shared_requests_for_agency_v1",
  "mark_agency_can_offer",
  "mark_booking_requests_seen",
  "mark_invitation_delivery_v1",
  "mark_service_requests_seen",
  "mark_worker_opportunities_seen_v1",
  "my_privacy_consent_history",
  "project_position_salary_avg",
  "propose_booking_request",
  "propose_booking_request_v3",
  "propose_contact_disclosure_request_v1",
  "propose_team_enquiry_v1",
  "provision_agency_worker_engagement_context",
  "provision_company_worker_engagement_context",
  "record_identity_resolution_event_v1",
  "record_talent_source_v1",
  "register_conversation_message_attachment",
  "register_customer_request_attachment",
  "register_journal_entry_photo",
  "remove_agency_client_v1",
  "remove_company_location_v1",
  "remove_worker_language_v1",
  "report_defect_v1",
  "request_service_offering",
  "request_worker_absence_v1",
  "requester_identities_for_provider",
  "reschedule_booking_proposal_v1",
  "resend_invitation_v1",
  "respond_agency_candidate_offer_v1",
  "respond_booking_request",
  "respond_booking_request_v2",
  "respond_booking_request_v3",
  "respond_contact_disclosure_request_v1",
  "respond_service_offering_request",
  "respond_team_enquiry_v1",
  "return_asset_v1",
  "review_journal_entries_batch",
  "review_journal_entry",
  "review_worker_absence_v1",
  "reviewable_journal_entry_ids",
  "revoke_agency_client_connection_v1",
  "revoke_conversation_participant",
  "revoke_invitation_v1",
  "save_agency_client_v1",
  "save_company_location_v1",
  "save_company_setup",
  "save_company_setup_v2",
  "save_customer_request",
  "save_customer_setup",
  "save_demand_draft",
  "save_self_declared_work_history_v1",
  "save_team_details_v1",
  "save_worker_availability_prefs",
  "save_worker_availability_prefs_v2",
  "save_worker_card",
  "save_worker_external_profile_v1",
  "save_worker_language_v1",
  "save_worker_opportunity_v1",
  "send_work_instruction",
  "send_work_instruction_to_project",
  "set_agency_worker_journal_review",
  "set_booking_response_deadline_v1",
  "set_business_public_profile_v1",
  "set_company_worker_journal_review",
  "set_contract_status_v1",
  "set_defect_status_v1",
  "set_demand_agency_client_v1",
  "set_docs_aggregate_consent",
  "set_external_profile_visibility_v1",
  "set_finance_record_status_v1",
  "set_follow_up_task_status_v1",
  "set_learning_review_item_status",
  "set_marketplace_listing_status_v1",
  "set_project_budget_status_v1",
  "set_project_budget_v1",
  "set_proposal_status_v1",
  "set_work_task_status_v1",
  "set_worker_operational_status",
  "share_request_with_agency_v1",
  "submit_agency_candidate_offer_v1",
  "submit_company_need_public_v1",
  "submit_demand_request",
  "submit_help_request_v1",
  "submit_privacy_request_v1",
  "transfer_asset_assignment_v1",
  "unsave_worker_opportunity_v1",
  "unshare_request_v1",
  "update_finance_record_v1",
  "update_marketplace_listing_v1",
  "update_project_stage_v1",
  "update_work_task_v1",
  "upsert_worker_readiness_item",
  "withdraw_agency_candidate_offer_v1",
  "withdraw_booking_request",
  "withdraw_booking_request_v2",
  "withdraw_profile_discoverability_consent",
  "withdraw_service_offering_request",
  "withdraw_team_enquiry_v1",
]  as const;

export type CanonicalAppRpc = (typeof CANONICAL_APP_RPCS)[number];
