import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
const S = JSON.parse(readFileSync("../../qa-state/chain-q6.json", "utf8"));
const U=process.env.SUPABASE_TEST_URL,A=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const r=await fetch(`${U}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:A,"Content-Type":"application/json"},body:JSON.stringify({email:S.accounts.st.email,password:"Pw-chain-qa-1!"})});
const jwt=(await r.json()).access_token;
const txt="QAq6 st probe";
const body={p_worker_id:S.accounts.st.workerId,p_engagement_context_id:"8b76e668-f96d-4181-9a95-f9b426cec99b",p_entry_type_slug:"freeform",p_profession_id:null,p_original_text:txt,p_original_language:"en",p_hash_prev:null,p_hash_self:createHash("sha256").update(txt).digest("hex"),p_visibility_scope:"closed",p_metrics:[],p_project_id:S.PROJECT3,p_project_explicit:true};
const x=await fetch(`${U}/rest/v1/rpc/create_journal_entry_full`,{method:"POST",headers:{apikey:A,Authorization:`Bearer ${jwt}`,"Content-Type":"application/json"},body:JSON.stringify(body)});
console.log(x.status, await x.text());
