import { chromium } from "@playwright/test";
import { readFileSync } from "node:fs";

const S = JSON.parse(readFileSync("../../qa-state/chain-q6.json", "utf8"));
const who = S.accounts.st;
const B = "http://127.0.0.1:3100";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 }, timezoneId: "UTC" })).newPage();
page.setDefaultTimeout(120000);
page.setDefaultNavigationTimeout(240000);
await page.goto(`${B}/en/auth/login`, { waitUntil: "domcontentloaded" });
await page.waitForLoadState("networkidle").catch(() => {});
await page.locator('input[type="email"]').fill(who.email);
await page.locator('input[type="password"]').fill("Pw-chain-qa-1!");
await page.locator('button[type="submit"]').first().click();
await page.waitForURL(/dashboard|onboarding/);
await page.goto(`${B}/en/dashboard/journal`, { waitUntil: "domcontentloaded" });
await page.locator("#journal-composer textarea").waitFor();
await page.waitForLoadState("networkidle").catch(() => {});
await page.locator("#journal-composer textarea").fill("QAq6 st-own-ws repro: fitted windows, worked 3 hours");
await page.getByRole("button", { name: /Read it back/i }).click();
const ctxSel = page.getByTestId("worklog-context");
await ctxSel.waitFor();
const opts = await ctxSel.locator("option").evaluateAll((os) => os.map((o) => [o.value, o.textContent]));
console.log("options", JSON.stringify(opts));
const own = opts.find((o) => /Owner/.test(o[1]));
await ctxSel.selectOption(own[0]);
await page.waitForTimeout(1500);
console.log("project text:", await page.locator('[data-testid^="worklog-project"]').allInnerTexts());
page.on("console", (m) => { if (m.type() === "error" && !/FORMATTING/.test(m.text())) console.log("[console.error]", m.text().slice(0, 300)); });
page.on("pageerror", (e) => console.log("[pageerror]", String(e).slice(0, 400)));
await page.getByTestId("worklog-save").click();
await page.waitForTimeout(8000);
console.log("confirm visible:", await page.getByTestId("worklog-confirm").count());
const comp = page.locator("#journal-composer");
console.log((await comp.innerText()).replace(/\s+/g, " ").slice(0, 800));
await page.screenshot({ path: "../../qa-shots/repro-save.png" });
await browser.close();
