import { chromium } from "@playwright/test";
const base = "http://127.0.0.1:3100";
const email = `qa.explore.${Date.now()}@local.test`;
const b = await chromium.launch();
const ctx = await b.newContext();
const page = await ctx.newPage(); page.setDefaultTimeout(240000); page.setDefaultNavigationTimeout(240000);
const dump = async (label) => {
  await page.waitForTimeout(4000);
  console.log("----" + label + "---- " + page.url());
  console.log((await page.locator("body").innerText()).slice(0, 2500));
  console.log(await page.evaluate(() => [...document.querySelectorAll("input,select,textarea,button")].map(e => [e.tagName, e.getAttribute("name"), e.getAttribute("data-testid"), e.type, (e.innerText||"").slice(0,30).replace(/\n/g," ")].join(" | ")).join("\n")));
  await page.screenshot({ path: "../../qa-shots/explore-" + label + ".png", fullPage: true });
};
await page.goto(base + "/en/auth/signup", { waitUntil: "domcontentloaded" });
await page.waitForLoadState("networkidle").catch(()=>{});
await page.locator('input[type="email"]').fill(email);
await page.locator('input[type="password"]').first().fill("E2ePass!23x");
await page.locator('input[type="password"]').nth(1).fill("E2ePass!23x");
await page.getByRole("button", { name: /Sign up/i }).click();
await page.waitForURL(/onboarding|dashboard/);
await page.waitForLoadState("networkidle").catch(()=>{}); await page.waitForTimeout(3000);
await page.getByTestId("onboarding-intent-hire").click();
await page.getByTestId("onboarding-intents-continue").click(); await page.getByTestId("onboarding-intents").waitFor({state:"detached", timeout: 30000}).catch(e=>console.log("still on step1"));
await dump("ob2");
await page.screenshot({path:"../../qa-shots/x.png"});
await page.locator('input[name="display_name"]').fill("QA Explore Owner");
await page.getByTestId("onboarding-country").click();
await page.waitForTimeout(1500);
console.log(await page.locator("body").innerText().then(t=>t.slice(0,600)));
await page.getByRole("option", { name: /Lithuania/i }).first().click().catch(async()=>{ await page.getByText(/^Lithuania/).first().click(); });
await page.getByRole("button", { name: /Finish/i }).click();
await page.waitForURL(/dashboard/);
await dump("after-finish");
await page.goto(base + "/en/dashboard/start/company", { waitUntil: "domcontentloaded" });
await dump("start-company");
await b.close();
