/**
 * Owner-review evidence generator for cross-sector Work Journal extraction.
 *
 * Runs the REAL deterministic engine (no AI, no DB, no network) over the exact
 * owner-review scenarios and prints a Markdown report. Re-runnable proof that a
 * construction worker's non-construction activities are detected, that an
 * existing profile skill is not duplicated, that a new skill surfaces as a
 * candidate, and that everything is Work-Journal evidence and never verified.
 *
 *   pnpm -F web exec tsx scripts/evidence-cross-sector.ts
 */
import { recognizeUniversal } from "@/lib/structuring/universal-recognition";
import { buildEntrySkillReview } from "@/lib/work-entry/entry-skill-review";

const out: string[] = [];
const log = (s = "") => out.push(s);

function showRecognition(title: string, text: string) {
  const r = recognizeUniversal(text);
  log(`### ${title}`);
  log("```");
  log(`input: ${text}`);
  for (const s of r.suggestions) {
    log(
      `  • ${s.label}  [domain=${s.domain} · sector=${s.sector} · evidence=${s.evidenceSource} · status=${s.status} · confirmed=${s.confirmed}]`,
    );
  }
  const sectors = [...new Set(r.suggestions.map((s) => s.sector))];
  log(`  sectors detected: ${sectors.join(", ") || "(none)"}`);
  log("```");
  log();
}

function showClassification(
  title: string,
  text: string,
  existing: { slug?: string | null; label: string }[],
) {
  const r = buildEntrySkillReview(text, existing);
  log(`### ${title}`);
  log("```");
  log(`input: ${text}`);
  log(`already declared: ${existing.map((e) => e.label).join(", ") || "(none)"}`);
  log(`existing skills (evidenced, not re-added): ${r.existingItems.map((i) => i.label).join(", ") || "(none)"}`);
  log(`new possible skills (candidates): ${r.newItems.map((i) => i.label).join(", ") || "(none)"}`);
  log(`performed activities (sector): ${r.activities.map((a) => a.sector).join(", ") || "(none)"}`);
  log(`evidence source: ${r.evidenceSource}`);
  log(`verification state: ${r.verificationState}`);
  log("```");
  log();
}

log("# Owner-review evidence — cross-sector Work Journal extraction (PR #485)");
log();
log("Generated by `scripts/evidence-cross-sector.ts` from the real engine. No AI, no DB, no network — pure deterministic lexicon.");
log();
log("## A construction worker's non-construction activities are detected");
log();
showRecognition("Construction worker logs cooking / meal preparation", "Tinkavau sieną, paskui gaminau maistą virtuvėje");
showRecognition("Construction worker logs gardening / grounds maintenance", "Tinkavau sieną, paskui pjoviau žolę ir genėjau krūmus");
showRecognition("Construction worker logs driving / transport / logistics", "Tinkavau sieną, paskui vairavau sunkvežimį ir vežiau krovinį maršrutu");

log("## Existing vs new, evidence source, verification state");
log();
showClassification(
  "Existing skill mentioned again is NOT duplicated",
  "Gaminau maistą virtuvėje",
  [{ label: "Maisto gaminimas" }],
);
showClassification(
  "A new non-profile skill appears as a new possible skill / candidate",
  "Aptarnavau klientus prie kasos",
  [],
);

console.log(out.join("\n"));