/**
 * Owner-review evidence for the PROVIDER-FREE location MVP (PR #484).
 * Runs the real pure location model (no Google, no provider, no network) over
 * the automatic + manual scenarios and prints a Markdown report.
 *   pnpm -F web exec tsx scripts/evidence-location-provider-free.ts
 */
import {
  RADIUS_OPTIONS,
  DEFAULT_RADIUS_KM,
  isUsableForSearch,
  normalizeRadius,
  summarizeLocation,
  type SelectedLocation,
} from "@/lib/location/location-model";

const out: string[] = [];
const log = (s = "") => out.push(s);

const auto: SelectedLocation = { source: "auto", lat: 54.6872, lng: 25.2797, country: null, region: null, address: null, radiusKm: 25, savedAt: 0 };
const manual: SelectedLocation = { source: "manual", lat: null, lng: null, country: "LT", region: "Vilnius", address: null, radiusKm: 50, savedAt: 0 };
const denied: SelectedLocation = { source: "manual", lat: null, lng: null, country: "PL", region: "Warszawa", address: null, radiusKm: 100, savedAt: 0 };

function show(title: string, loc: SelectedLocation) {
  const s = summarizeLocation(loc);
  log(`### ${title}`);
  log("```");
  log(`source: ${s.source}`);
  log(`where: ${s.where}`);
  log(`radius: ${s.radiusKm} km`);
  log(`has browser coordinates: ${s.hasCoords}`);
  log(`usable for job search (no provider): ${s.usable}`);
  log("```");
  log();
}

log("# Owner-review evidence — provider-free location (PR #484)");
log();
log("Generated by `scripts/evidence-location-provider-free.ts` from the real pure model. No Google, no paid provider, no network, no API key.");
log();
show("Automatic location (browser geolocation)", auto);
show("Manual location (country + city/region, no geocoding)", manual);
show("Geolocation denied → manual fallback still works", denied);
log("### Radius selection");
log("```");
log(`options: ${RADIUS_OPTIONS.join(" / ")} km   (default ${DEFAULT_RADIUS_KM} km)`);
log(`normalizeRadius(30) -> ${normalizeRadius(30)} ; normalizeRadius(60) -> ${normalizeRadius(60)}`);
log("```");
log();
log("### Provider-free continuation");
log("```");
log(`manual country-only usable without coordinates: ${isUsableForSearch(manual)}`);
log(`no Google Maps key required: true (the model imports no provider)`);
log("```");
console.log(out.join("\n"));