/**
 * One-time generator (NOT in the build pipeline). World edition of
 * scripts/gen-europe-geo.ts: reads the low-res world-atlas countries-110m
 * TopoJSON, projects the FULL world (equirectangular, Antarctica cropped),
 * decimates aggressively to keep the generated module small, and writes a
 * dependency-free static module: components/app/world-geo.ts
 *
 * Tiers: `target` = the 9 current market directions + GE + US;
 *        `context` = every other country (world scale, not focus).
 *
 * Run: pnpm -C apps/web exec tsx scripts/gen-world-geo.ts
 * world-atlas + topojson-client are devDependencies used ONLY here — the
 * runtime LiveWorldMap imports the generated file and ships no geo deps.
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const topo: any = require("world-atlas/countries-110m.json");

const W = 1000;
const LNG0 = -180;
const LNG1 = 180;
const LAT0 = -56; // crop Antarctica
const LAT1 = 84;
const H = Math.round(((LAT1 - LAT0) / (LNG1 - LNG0)) * W); // 389
const project = (lng: number, lat: number): [number, number] => [
  ((lng - LNG0) / (LNG1 - LNG0)) * W,
  ((LAT1 - lat) / (LAT1 - LAT0)) * H,
];

const norm = (s: string) => s.toLowerCase().replace(/[^a-z]/g, "");

/** Current 9 market directions + Georgia + United States. */
const TARGET_NAMES = [
  "Netherlands",
  "Germany",
  "Denmark",
  "Sweden",
  "Norway",
  "Poland",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Georgia",
  "United States of America",
];
const TARGET = new Set(TARGET_NAMES.map(norm));
const CODE: Record<string, string> = {
  netherlands: "NL",
  germany: "DE",
  denmark: "DK",
  sweden: "SE",
  norway: "NO",
  poland: "PL",
  lithuania: "LT",
  latvia: "LV",
  estonia: "EE",
  georgia: "GE",
  unitedstatesofamerica: "US",
};
const SKIP = new Set(["Antarctica"].map(norm));

type Tier = "target" | "context";

const CAP: Record<Tier, number> = { target: 420, context: 110 };

/**
 * Project + decimate one ring into path segments. Splits the path (new `M`)
 * whenever consecutive points jump more than half the map width — that is an
 * antimeridian crossing (Chukotka, the Aleutians, Fiji), which would
 * otherwise draw a horizontal slash across the whole map.
 */
function ringPath(ring: number[][], cap: number): string | null {
  let pts = ring.map(([lng, lat]) => project(lng, lat));
  const xs = pts.map((p) => p[0]);
  const ys = pts.map((p) => p[1]);
  if (
    Math.max(...xs) < -20 ||
    Math.min(...xs) > W + 20 ||
    Math.max(...ys) < -20 ||
    Math.min(...ys) > H + 20
  )
    return null;
  if (pts.length > cap) {
    const step = Math.ceil(pts.length / cap);
    pts = pts.filter((_, i) => i % step === 0 || i === pts.length - 1);
  }
  if (pts.length < 4) return null;
  const r = (v: number) => Math.round(v);
  let d = "";
  for (let i = 0; i < pts.length; i++) {
    const jump = i > 0 && Math.abs(pts[i][0] - pts[i - 1][0]) > W / 2;
    const cmd = i === 0 || jump ? "M" : "L";
    d += `${i ? " " : ""}${cmd}${r(pts[i][0])} ${r(pts[i][1])}`;
  }
  return `${d}Z`;
}

const fc = feature(
  topo,
  topo.objects.countries,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
) as any;

type Row = { code: string; name: string; tier: Tier; d: string };
const rows: Row[] = [];
let totalPoints = 0;

for (const f of fc.features) {
  const name: string = f.properties?.name ?? "";
  if (!name || SKIP.has(norm(name))) continue;
  const tier: Tier = TARGET.has(norm(name)) ? "target" : "context";
  const geom = f.geometry;
  if (!geom) continue;
  const polys: number[][][][] =
    geom.type === "Polygon" ? [geom.coordinates] : geom.coordinates;
  const parts: string[] = [];
  let perCountryCap = CAP[tier];
  for (const poly of polys) {
    for (const ring of poly) {
      const d = ringPath(ring, Math.max(24, Math.floor(perCountryCap / 2)));
      if (d) {
        parts.push(d);
        totalPoints += (d.match(/[ML]/g)?.length ?? 0);
        perCountryCap = Math.max(24, perCountryCap - 40);
      }
    }
  }
  if (!parts.length) continue;
  rows.push({
    code: CODE[norm(name)] ?? norm(name).slice(0, 3).toUpperCase(),
    name,
    tier,
    d: parts.join(" "),
  });
}

rows.sort((a, b) => {
  const order = { context: 0, target: 1 } as const;
  return order[a.tier] - order[b.tier];
});

const out = `// GENERATED by scripts/gen-world-geo.ts — do not edit by hand.
// Source: world-atlas countries-110m (devDependency, not shipped).
// Equirectangular projection, full world (Antarctica cropped),
// viewBox 0 0 ${W} ${H}. Total polygon points: ${totalPoints}.

export const WORLD_W = ${W};
export const WORLD_H = ${H};
const LNG0 = ${LNG0};
const LNG1 = ${LNG1};
const LAT0 = ${LAT0};
const LAT1 = ${LAT1};

/** Same projection the country paths were generated with — any marker MUST
 *  use this so it lands in the right place. */
export function projectWorld(lng: number, lat: number): [number, number] {
  return [
    ((lng - LNG0) / (LNG1 - LNG0)) * WORLD_W,
    ((LAT1 - lat) / (LAT1 - LAT0)) * WORLD_H,
  ];
}

export type WorldTier = "target" | "context";
export type WorldCountry = {
  code: string;
  name: string;
  tier: WorldTier;
  d: string;
};

export const WORLD_GEO: WorldCountry[] = ${JSON.stringify(rows)};
`;

const dest = join(process.cwd(), "components", "app", "world-geo.ts");
writeFileSync(dest, out);
console.log(
  `world-geo.ts written: ${rows.length} countries, ~${totalPoints} points, ${Buffer.byteLength(out)} bytes.`,
);
