import type { getTranslations } from "next-intl/server";

import type { ChatLabels } from "./conversation-chat";
import type { WorkLogLabels } from "@/components/app/conversation/worker-worklog-flow";

type T = Awaited<ReturnType<typeof getTranslations>>;

const CHAT_KEYS = [
  "headerTitle",
  "assistantName",
  "speakerYou",
  "navChat",
  "navJournal",
  "navMessages",
  "navCalendar",
  "navProfile",
  "composerPlaceholder",
  "send",
  "attach",
  "greeting",
  "chipCv",
  "chipJobs",
  "chipProfile",
  "chipOffers",
  "chipLang",
  "chipExp",
  "chipEdu",
  "chipCard",
  "chipPrefs",
  "offersEmpty",
  "searchAskCriteria",
  "playerCardAfterLog",
  "playerCardOpened",
  // `userFindWork` doubles as the CONTINUE label on the saved criteria form
  // (beta audit W-J1): the button that actually runs the promised search must
  // say "Find work", not "Add another". Key already exists in all catalogues.
  "fallback",
  "userCv",
  "userProfile",
  "userOffers",
  "userJobs",
  "userFindWork",
  "chipLogWork",
  "userLogWork",
  "chipAgenda",
  "userAgenda",
  "chipNeedWorkers",
  "chipCandidates",
  "chipCompanyHub",
  // M10 — education-shaped starters for a training-provider workspace.
  // `learnerGreetingContext` carries an `{institution}` placeholder, so like
  // `greetingNamed` it is resolved by the server caller that knows the name.
  "chipEduInviteLearner",
  "chipEduCapabilities",
  "companyDemandNext",
  "chipTasks",
  "clarifyWorkLog",
  "calendarHint",
  "messagesHint",
  "reminderBlocked",
  "translateBlocked",
  // The administration areas that now open on an explicit ?area= instead
  // of unrolling under every visit to /dashboard/network. Gating a surface
  // is only half the job: these are how the sentences that mean them still
  // reach them.
  // §2 — the person is ONE. Somebody who HOLDS the company role is an
  // employer even while their active workspace is personal, so a sentence
  // about hiring must not die in the not-understood fallback.
  "employerBridgeHint",
  // §33 — a request for a JOB TO BE DONE is not a request to fill a job.
  "serviceNeedHint",
  "chipServiceRequests",
  // §2: "kas susidomėjo?" means two real things for a dual-role person.
  "interestInboxAmbiguous",
  "chipInterestOnMyNeeds",
  "chipMyOwnInterest",
  // The one sentence that means START an organization (as opposed to
  // `company-overview`, which means LOOK AT one).
  "createOrganizationHint",
  "chipCreateOrganization",
  // The credit ledger, reachable by asking rather than only by searching.
  // The command finder already answered the SHORT query ("lmc"); a sentence
  // walked past it, because that matcher is a search box and not a router.
  "lmcHint",
  "chipLmc",
  "adminRouteHint",
  "adminApprovalsChip",
  "adminRequestsChip",
  // The timesheet area of the planning page, reachable by sentence
  // (self-serve approval-template closure slice).
  "timesheetsChip",
  // §9 chat-first coverage — six domains that shipped reachable only by URL.
  // They reuse `adminRouteHint` for the sentence and add one chip label each.
  "timesheetImportChip",
  "workHoursChip",
  "absencesChip",
  "documentsChip",
  "marketMapChip",
  "activityChip",
  "writeEmployerHint",
  // W7 slice 2 — intent-aware attach.
  "attachChoice",
  "chipAttachPhoto",
  "chipAttachCv",
  "userAttachPhoto",
  // W6 slice 3D — the experience entry point. Four states because the answer
  // is always the person's REAL state, never a prompt to write something.
  "experiencesEligible",
  "experiencesAllSubmitted",
  "experiencesNothingYet",
  "experiencesUnavailable",
  "experienceLeave",
  // W8 — the employer's hiring stage. Five states because "no company",
  // "no needs yet" and "the read failed" are three different truths, and
  // none of them may be rendered as one of the others.
  "userCandidates",
  "candidatesOpened",
  "candidatesNoDemands",
  "candidatesNoCompany",
  "candidatesUnavailable",
  // W11 — projects and the assignment step. Same rule as above: "no project",
  // "no company" and "the read failed" are three different truths.
  "chipProjects",
  "userProjects",
  "projectsOpened",
  "projectsNone",
  "projectsNoCompany",
  "projectsUnavailable",
  "assignPickWorker",
  "assignNoWorkers",
  "assignUnavailable",
  "assignDone",
  "assignFailed",
  // §7.1 — work relationships. Same rule again: "none recorded", "no company"
  // and "the read failed" are three different truths and stay three sentences.
  "chipEngagements",
  "userEngagements",
  "engagementsOpened",
  "engagementsNone",
  "engagementsNoCompany",
  "engagementsUnavailable",
  // Agency / student / institution vocabulary (real recruiter pilot, 2026-09-04).
  "fallbackCompany",
  "fallbackAgency",
  "fallbackEducation",
  // Owner contract 2026-09-04 §5–§6: the composed capability sentence lives
  // on the server (`fallbackComposed`, `workspaceIntro`, `capPhrase*` are
  // resolved in the page); no new client label.
  "agencyInviteClientAsk",
  "agencyInviteClientPrefilled",
  "agencyInviteClientDone",
  "agencyInviteCandidateAsk",
  "agencyInviteCandidateDone",
  "agencyInviteCandidateExists",
  "agencyNotAgencyWorkspace",
  "agencySwitchHint",
  "agencyClientDemandIntro",
  "agencyClientDemandNone",
  "agencyProposalsIntro",
  "agencyProposalsNone",
  "agencyProposeAsk",
  "agencyProposeDone",
  "agencyRosterEmpty",
  "agencyUnavailable",
  "agencyNext",
  "chipInviteClient",
  "chipInviteCandidate",
  "chipClientDemand",
  "chipProposalStatus",
  "chipProposeFor",
  "userClientDemand",
  "userProposalStatus",
  "learningCompassHint",
  "chipLearningCompass",
  "inviteStudentHint",
  "chipInviteStudent",
  "programmesHint",
  "chipProgrammes",
  // Education by sentence (owner contract 2026-09-04 §15).
  "eduInviteAsk",
  "eduInviteDone",
  "eduInviteCreatedNoEmail",
  "eduProgrammesIntro",
  "eduProgrammesNone",
  "eduProgrammeLine",
  "eduProgrammeCreated",
  "eduCohortPick",
  "eduCohortCreated",
  "eduAssignNoCohort",
  "eduAssignNoLearners",
  "eduAssignDone",
  "eduNotInstitution",
  "eduUnavailable",
  "eduNext",
  "chipCreateProgramme",
  "chipCreateCohort",
  "chipAssignLearner",
  // My Space (owner contract 2026-09-04 §4C).
  "mySpaceTitle",
  "chipManagePins",
  "pinAsk",
  "chipPinYes",
  "chipPinNo",
  "pinDone",
  "pinCap",
  "pinUnavailable",
  "pinsManageIntro",
  "pinsNone",
  "unpinPrefix",
  "unpinDone",
  "pinFirstPrefix",
  "reorderDone",
  "projectCreateIntro",
  "projectCreatedNext",
  "clientOffersIntro",
  "clientOffersNone",
  "chipOfferAccept",
  "chipOfferDecline",
  "offerAccepted",
  "offerDeclined",
  "offerDecisionFailed",
  "documentAddIntro",
  "documentAddDone",
  "documentAddUnavailable",
  "documentFileOffer",
  "documentFileChoose",
  "documentFileSubmit",
  "documentFileUploading",
  "documentFileSkip",
  "documentFileUploaded",
  "documentFileTooLarge",
  "documentFileUnsupported",
  "documentFileFailed",
  "cvExportHint",
  "chipCvSheet",
  "taskCreateIntro",
  "taskCreatedNext",
  "capacityIntro",
  "capacityFree",
  "capacityBusyUntil",
  "capacityAbsencesUnknown",
  "capacityEmpty",
  "capacityUnavailable",
  "chipAddTask",
  "workerProjectsIntro",
  "workerProjectsEnded",
  "chipOpenProjectPrefix",
  "workerProjectAsks",
  "askOwnReady",
  "askOwnExpiring",
  "askOwnNone",
  "chipRecordDocument",
  "askReplyIntro",
  "askReplyIntroUnnamed",
  "stageAsk",
  "stageNotFound",
  "stageNone",
  "stageDone",
  "stageStarted",
  "stageBlocked",
  "stageFailed",
  "chipStagePrefix",
  "taskAsk",
  "taskNotFound",
  "taskNone",
  "taskUnavailable",
  "taskDone",
  "taskStarted",
  "taskBlocked",
  "taskFailed",
  "chipTaskPrefix",
  "riskIntro",
  "riskLine",
  "riskOkLine",
  "riskUnknownLine",
  "riskNobody",
  "riskNone",
  "riskUnavailable",
  "chipCreateProject",
  "readinessIntro",
  "readinessRepliedSuffix",
  "readinessReadyLine",
  "readinessGapLine",
  "readinessNoChecklist",
  "readinessNoPeople",
  "readinessAsk",
  "readinessNotFound",
  "readinessUnavailable",
  "chipReadinessPrefix",
  "chipOpenOperations",
  "missingName",
  "missingDeclaredSkills",
  "missingEvidence",
  "blockedSuffix",
  "readinessSeedChip",
  "readinessSeeded",
  "readinessGotChip",
  "readinessGotDone",
  "readinessAskChip",
  "readinessAskDone",
  "readinessRequestBody",
  "readinessWriteFailed",
  "confirmIntro",
  "confirmLine",
  "confirmChip",
  "confirmDone",
  "confirmNone",
  "confirmNotEnabled",
  "confirmEnableChip",
  "confirmEnabled",
  "confirmFailed",
  "confirmUnavailable",
  "chipOpenInbox",
  "moveNotFound",
  "moveNoOptions",
  "moveAskWorker",
  "moveConfirmChip",
  "moveCancelChip",
  "moveFailed",
  "chipMovePrefix",
] as const;

const WORKLOG_KEYS = [
  "understood",
  "loading",
  "noContext",
  "noContextCta",
  "noWorker",
  "notAuthed",
  "labelDate",
  "labelTime",
  "labelBreak",
  "labelHours",
  "labelSite",
  "labelNotes",
  "labelContext",
  // Rule C of the engagement-context hierarchy: several are legitimately
  // possible, so the flow asks instead of preselecting one.
  "contextChoose",
  "contextAmbiguous",
  "save",
  "cancel",
  "working",
  "confirmTitle",
  "saved",
  "errorGeneric",
  "minutesUnit",
  // PR-C "what changed" completion summary (real pipeline outcome only).
  "addedSkillPrefix",
  "strengthenedSkillPrefix",
  "pendingConfirmPrefix",
  "cvUpdatedNote",
  "matchingNote",
  "viewOpportunities",
  "pipelineFailedNote",
] as const;

/** Resolve the flat chat label bag from a `conversation.chat`-scoped translator.
 *
 *  `greetingNamed` carries a `{name}` placeholder, so it is resolved separately
 *  by the caller that actually knows the name — it must never be rendered with
 *  the raw placeholder showing. */
export function resolveChatLabels(t: T): ChatLabels {
  const out = {} as Record<(typeof CHAT_KEYS)[number], string>;
  for (const k of CHAT_KEYS) out[k] = t(k);
  return out as ChatLabels;
}

/** Resolve the work-log label bag from a `conversation.worklog`-scoped translator. */
export function resolveWorkLogLabels(t: T): WorkLogLabels {
  const out = {} as Record<(typeof WORKLOG_KEYS)[number], string>;
  for (const k of WORKLOG_KEYS) out[k] = t(k);
  return out as WorkLogLabels;
}
