/// <reference types="expo/types" />

/**
 * The environment this app reads — typed, and deliberately short.
 *
 * `EXPO_PUBLIC_*` variables are INLINED INTO THE SHIPPED BUNDLE at build time.
 * That is why this list is the whole list: naming a variable here is a
 * statement that its value may sit in a binary on someone's phone forever.
 * Nothing secret may ever be added.
 *
 * This is a separate file from `expo-env.d.ts` on purpose. That one is
 * generated by the Expo CLI, git-ignored, and overwritten without warning —
 * these declarations were written into it once and silently lost the first
 * time the dev server started.
 */
declare namespace NodeJS {
  interface ProcessEnv {
    readonly EXPO_PUBLIC_SUPABASE_URL?: string;
    readonly EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    readonly EXPO_PUBLIC_API_BASE_URL?: string;
  }
}
