-- ════════════════════════════════════════════════════════════════════════
-- 0014_workers_owner_write_grant.sql — let the owning user persist their
-- own worker row (additive, non-destructive).
--
-- The `workers` table has shipped since M0 with `bio`, `headline`, and other
-- owner-editable fields, and 0001 already created a `workers_update` RLS
-- policy restricting rows to `profile_id = auth.uid() or is_admin()`. But
-- this project uses EXPLICIT grants (per 0004 / migration 0013's header note)
-- so without GRANT INSERT, UPDATE the policy is unreachable from the app
-- session — any update silently fails at the SQL permission layer before RLS
-- runs.
--
-- This migration adds only the SQL-level INSERT/UPDATE grants. Row scope is
-- still enforced by the existing RLS policies (see 0001 lines 420–433). No
-- schema changes; no data mutation.
--
-- Validated by the registered-user core loop slice (PR feat/cc/registered-user-core-loop-v1)
-- which wires the text-first profile composer to persist its narrative into
-- `workers.bio` / `workers.headline`.
-- ════════════════════════════════════════════════════════════════════════

grant insert, update on public.workers to authenticated;
