-- ============================================================================
-- 20260922120000 — countries: every ISO-3166-1 alpha-2 code (global-access rule v1)
--
-- OWNER RULE (2026-09-22): LabourMarket.ai is GLOBAL by default. MARKET PRIORITY
-- != ACCESS PERMISSION. `organizations.country` and `engagement_contexts.country_code`
-- carry a FOREIGN KEY to `public.countries(code)`, and the table held 10 rows
-- (DE DK EE FI LT LV NL NO PL SE) — so a company in Ireland, Vietnam or the
-- United States could not exist in the system. That was a silent country gate,
-- not a product decision.
--
-- WHAT THIS DOES: seeds every officially assigned ISO code (the same 249-code
-- registry as apps/web/lib/location/country-model.ts, names from CLDR lt/en)
-- with `is_target_market = false`. Existing rows are untouched (`on conflict do
-- nothing`), so the 10 target markets keep `is_target_market = true`. Reference
-- data only: no listing, count, availability or market claim is made by a row.
--
-- WHAT THIS DOES NOT DO: it does not widen the anonymous public intake
-- allowlist (submit_company_need_public_v1, SECURITY DEFINER — separate owner
-- gate), the country_document_requirements CHECK, or the market_rate_averages
-- CHECK. Those are explicit, documented, narrowly scoped restrictions and are
-- listed in the audit, not changed here.
--
-- ROLLBACK (down): supabase/rollbacks/20260922120000_countries_all_iso_v1.down.sql
-- deletes ONLY rows this migration inserted: is_target_market = false AND no
-- organizations / engagement_contexts row references the code (a referenced
-- row means a real company now lives there and must not be orphaned).
--
-- GATE: additive insert ... on conflict do nothing (GREEN by shape). Apply only
-- via the owner-gated production path (Supabase MCP apply_migration after the
-- PR gate report), never `db push`. Precedent: 20260717130000 (six markets).
-- ============================================================================

insert into public.countries (code, name_lt, name_en, is_target_market) values
  ('AD', 'Andora', 'Andorra', false),
  ('AE', 'Jungtiniai Arabų Emyratai', 'United Arab Emirates', false),
  ('AF', 'Afganistanas', 'Afghanistan', false),
  ('AG', 'Antigva ir Barbuda', 'Antigua & Barbuda', false),
  ('AI', 'Angilija', 'Anguilla', false),
  ('AL', 'Albanija', 'Albania', false),
  ('AM', 'Armėnija', 'Armenia', false),
  ('AO', 'Angola', 'Angola', false),
  ('AQ', 'Antarktida', 'Antarctica', false),
  ('AR', 'Argentina', 'Argentina', false),
  ('AS', 'Amerikos Samoa', 'American Samoa', false),
  ('AT', 'Austrija', 'Austria', false),
  ('AU', 'Australija', 'Australia', false),
  ('AW', 'Aruba', 'Aruba', false),
  ('AX', 'Alandų Salos', 'Åland Islands', false),
  ('AZ', 'Azerbaidžanas', 'Azerbaijan', false),
  ('BA', 'Bosnija ir Hercegovina', 'Bosnia & Herzegovina', false),
  ('BB', 'Barbadosas', 'Barbados', false),
  ('BD', 'Bangladešas', 'Bangladesh', false),
  ('BE', 'Belgija', 'Belgium', false),
  ('BF', 'Burkina Fasas', 'Burkina Faso', false),
  ('BG', 'Bulgarija', 'Bulgaria', false),
  ('BH', 'Bahreinas', 'Bahrain', false),
  ('BI', 'Burundis', 'Burundi', false),
  ('BJ', 'Beninas', 'Benin', false),
  ('BL', 'Sen Bartelemi', 'St. Barthélemy', false),
  ('BM', 'Bermuda', 'Bermuda', false),
  ('BN', 'Brunėjus', 'Brunei', false),
  ('BO', 'Bolivija', 'Bolivia', false),
  ('BQ', 'Karibų Nyderlandai', 'Caribbean Netherlands', false),
  ('BR', 'Brazilija', 'Brazil', false),
  ('BS', 'Bahamos', 'Bahamas', false),
  ('BT', 'Butanas', 'Bhutan', false),
  ('BV', 'Buvė Sala', 'Bouvet Island', false),
  ('BW', 'Botsvana', 'Botswana', false),
  ('BY', 'Baltarusija', 'Belarus', false),
  ('BZ', 'Belizas', 'Belize', false),
  ('CA', 'Kanada', 'Canada', false),
  ('CC', 'Kokosų (Kilingo) Salos', 'Cocos (Keeling) Islands', false),
  ('CD', 'Kongas-Kinšasa', 'Congo - Kinshasa', false),
  ('CF', 'Centrinės Afrikos Respublika', 'Central African Republic', false),
  ('CG', 'Kongas-Brazavilis', 'Congo - Brazzaville', false),
  ('CH', 'Šveicarija', 'Switzerland', false),
  ('CI', 'Dramblio Kaulo Krantas', 'Côte d’Ivoire', false),
  ('CK', 'Kuko Salos', 'Cook Islands', false),
  ('CL', 'Čilė', 'Chile', false),
  ('CM', 'Kamerūnas', 'Cameroon', false),
  ('CN', 'Kinija', 'China', false),
  ('CO', 'Kolumbija', 'Colombia', false),
  ('CR', 'Kosta Rika', 'Costa Rica', false),
  ('CU', 'Kuba', 'Cuba', false),
  ('CV', 'Žaliasis Kyšulys', 'Cape Verde', false),
  ('CW', 'Kiurasao', 'Curaçao', false),
  ('CX', 'Kalėdų Sala', 'Christmas Island', false),
  ('CY', 'Kipras', 'Cyprus', false),
  ('CZ', 'Čekija', 'Czechia', false),
  ('DE', 'Vokietija', 'Germany', false),
  ('DJ', 'Džibutis', 'Djibouti', false),
  ('DK', 'Danija', 'Denmark', false),
  ('DM', 'Dominika', 'Dominica', false),
  ('DO', 'Dominikos Respublika', 'Dominican Republic', false),
  ('DZ', 'Alžyras', 'Algeria', false),
  ('EC', 'Ekvadoras', 'Ecuador', false),
  ('EE', 'Estija', 'Estonia', false),
  ('EG', 'Egiptas', 'Egypt', false),
  ('EH', 'Vakarų Sachara', 'Western Sahara', false),
  ('ER', 'Eritrėja', 'Eritrea', false),
  ('ES', 'Ispanija', 'Spain', false),
  ('ET', 'Etiopija', 'Ethiopia', false),
  ('FI', 'Suomija', 'Finland', false),
  ('FJ', 'Fidžis', 'Fiji', false),
  ('FK', 'Folklando salos', 'Falkland Islands', false),
  ('FM', 'Mikronezija', 'Micronesia', false),
  ('FO', 'Farerų Salos', 'Faroe Islands', false),
  ('FR', 'Prancūzija', 'France', false),
  ('GA', 'Gabonas', 'Gabon', false),
  ('GB', 'Jungtinė Karalystė', 'United Kingdom', false),
  ('GD', 'Grenada', 'Grenada', false),
  ('GE', 'Gruzija', 'Georgia', false),
  ('GF', 'Prancūzijos Gviana', 'French Guiana', false),
  ('GG', 'Gernsis', 'Guernsey', false),
  ('GH', 'Gana', 'Ghana', false),
  ('GI', 'Gibraltaras', 'Gibraltar', false),
  ('GL', 'Grenlandija', 'Greenland', false),
  ('GM', 'Gambija', 'Gambia', false),
  ('GN', 'Gvinėja', 'Guinea', false),
  ('GP', 'Gvadelupa', 'Guadeloupe', false),
  ('GQ', 'Pusiaujo Gvinėja', 'Equatorial Guinea', false),
  ('GR', 'Graikija', 'Greece', false),
  ('GS', 'Pietų Džordžija ir Pietų Sandvičo salos', 'South Georgia & South Sandwich Islands', false),
  ('GT', 'Gvatemala', 'Guatemala', false),
  ('GU', 'Guamas', 'Guam', false),
  ('GW', 'Bisau Gvinėja', 'Guinea-Bissau', false),
  ('GY', 'Gajana', 'Guyana', false),
  ('HK', 'Ypatingasis Administracinis Kinijos Regionas Honkongas', 'Hong Kong SAR China', false),
  ('HM', 'Herdo ir Makdonaldo Salos', 'Heard & McDonald Islands', false),
  ('HN', 'Hondūras', 'Honduras', false),
  ('HR', 'Kroatija', 'Croatia', false),
  ('HT', 'Haitis', 'Haiti', false),
  ('HU', 'Vengrija', 'Hungary', false),
  ('ID', 'Indonezija', 'Indonesia', false),
  ('IE', 'Airija', 'Ireland', false),
  ('IL', 'Izraelis', 'Israel', false),
  ('IM', 'Meno Sala', 'Isle of Man', false),
  ('IN', 'Indija', 'India', false),
  ('IO', 'Indijos Vandenyno Britų Sritis', 'British Indian Ocean Territory', false),
  ('IQ', 'Irakas', 'Iraq', false),
  ('IR', 'Iranas', 'Iran', false),
  ('IS', 'Islandija', 'Iceland', false),
  ('IT', 'Italija', 'Italy', false),
  ('JE', 'Džersis', 'Jersey', false),
  ('JM', 'Jamaika', 'Jamaica', false),
  ('JO', 'Jordanija', 'Jordan', false),
  ('JP', 'Japonija', 'Japan', false),
  ('KE', 'Kenija', 'Kenya', false),
  ('KG', 'Kirgizija', 'Kyrgyzstan', false),
  ('KH', 'Kambodža', 'Cambodia', false),
  ('KI', 'Kiribatis', 'Kiribati', false),
  ('KM', 'Komorai', 'Comoros', false),
  ('KN', 'Sent Kitsas ir Nevis', 'St. Kitts & Nevis', false),
  ('KP', 'Šiaurės Korėja', 'North Korea', false),
  ('KR', 'Pietų Korėja', 'South Korea', false),
  ('KW', 'Kuveitas', 'Kuwait', false),
  ('KY', 'Kaimanų Salos', 'Cayman Islands', false),
  ('KZ', 'Kazachstanas', 'Kazakhstan', false),
  ('LA', 'Laosas', 'Laos', false),
  ('LB', 'Libanas', 'Lebanon', false),
  ('LC', 'Sent Lusija', 'St. Lucia', false),
  ('LI', 'Lichtenšteinas', 'Liechtenstein', false),
  ('LK', 'Šri Lanka', 'Sri Lanka', false),
  ('LR', 'Liberija', 'Liberia', false),
  ('LS', 'Lesotas', 'Lesotho', false),
  ('LT', 'Lietuva', 'Lithuania', false),
  ('LU', 'Liuksemburgas', 'Luxembourg', false),
  ('LV', 'Latvija', 'Latvia', false),
  ('LY', 'Libija', 'Libya', false),
  ('MA', 'Marokas', 'Morocco', false),
  ('MC', 'Monakas', 'Monaco', false),
  ('MD', 'Moldova', 'Moldova', false),
  ('ME', 'Juodkalnija', 'Montenegro', false),
  ('MF', 'Sen Martenas', 'St. Martin', false),
  ('MG', 'Madagaskaras', 'Madagascar', false),
  ('MH', 'Maršalo Salos', 'Marshall Islands', false),
  ('MK', 'Šiaurės Makedonija', 'North Macedonia', false),
  ('ML', 'Malis', 'Mali', false),
  ('MM', 'Mianmaras (Birma)', 'Myanmar (Burma)', false),
  ('MN', 'Mongolija', 'Mongolia', false),
  ('MO', 'Ypatingasis Administracinis Kinijos Regionas Makao', 'Macao SAR China', false),
  ('MP', 'Marianos Šiaurinės Salos', 'Northern Mariana Islands', false),
  ('MQ', 'Martinika', 'Martinique', false),
  ('MR', 'Mauritanija', 'Mauritania', false),
  ('MS', 'Montseratas', 'Montserrat', false),
  ('MT', 'Malta', 'Malta', false),
  ('MU', 'Mauricijus', 'Mauritius', false),
  ('MV', 'Maldyvai', 'Maldives', false),
  ('MW', 'Malavis', 'Malawi', false),
  ('MX', 'Meksika', 'Mexico', false),
  ('MY', 'Malaizija', 'Malaysia', false),
  ('MZ', 'Mozambikas', 'Mozambique', false),
  ('NA', 'Namibija', 'Namibia', false),
  ('NC', 'Naujoji Kaledonija', 'New Caledonia', false),
  ('NE', 'Nigeris', 'Niger', false),
  ('NF', 'Norfolko sala', 'Norfolk Island', false),
  ('NG', 'Nigerija', 'Nigeria', false),
  ('NI', 'Nikaragva', 'Nicaragua', false),
  ('NL', 'Nyderlandai', 'Netherlands', false),
  ('NO', 'Norvegija', 'Norway', false),
  ('NP', 'Nepalas', 'Nepal', false),
  ('NR', 'Nauru', 'Nauru', false),
  ('NU', 'Niujė', 'Niue', false),
  ('NZ', 'Naujoji Zelandija', 'New Zealand', false),
  ('OM', 'Omanas', 'Oman', false),
  ('PA', 'Panama', 'Panama', false),
  ('PE', 'Peru', 'Peru', false),
  ('PF', 'Prancūzijos Polinezija', 'French Polynesia', false),
  ('PG', 'Papua Naujoji Gvinėja', 'Papua New Guinea', false),
  ('PH', 'Filipinai', 'Philippines', false),
  ('PK', 'Pakistanas', 'Pakistan', false),
  ('PL', 'Lenkija', 'Poland', false),
  ('PM', 'Sen Pjeras ir Mikelonas', 'St. Pierre & Miquelon', false),
  ('PN', 'Pitkerno salos', 'Pitcairn Islands', false),
  ('PR', 'Puerto Rikas', 'Puerto Rico', false),
  ('PS', 'Palestinos teritorija', 'Palestinian Territories', false),
  ('PT', 'Portugalija', 'Portugal', false),
  ('PW', 'Palau', 'Palau', false),
  ('PY', 'Paragvajus', 'Paraguay', false),
  ('QA', 'Kataras', 'Qatar', false),
  ('RE', 'Reunjonas', 'Réunion', false),
  ('RO', 'Rumunija', 'Romania', false),
  ('RS', 'Serbija', 'Serbia', false),
  ('RU', 'Rusija', 'Russia', false),
  ('RW', 'Ruanda', 'Rwanda', false),
  ('SA', 'Saudo Arabija', 'Saudi Arabia', false),
  ('SB', 'Saliamono Salos', 'Solomon Islands', false),
  ('SC', 'Seišeliai', 'Seychelles', false),
  ('SD', 'Sudanas', 'Sudan', false),
  ('SE', 'Švedija', 'Sweden', false),
  ('SG', 'Singapūras', 'Singapore', false),
  ('SH', 'Šv. Elenos Sala', 'St. Helena', false),
  ('SI', 'Slovėnija', 'Slovenia', false),
  ('SJ', 'Svalbardas ir Janas Majenas', 'Svalbard & Jan Mayen', false),
  ('SK', 'Slovakija', 'Slovakia', false),
  ('SL', 'Siera Leonė', 'Sierra Leone', false),
  ('SM', 'San Marinas', 'San Marino', false),
  ('SN', 'Senegalas', 'Senegal', false),
  ('SO', 'Somalis', 'Somalia', false),
  ('SR', 'Surinamas', 'Suriname', false),
  ('SS', 'Pietų Sudanas', 'South Sudan', false),
  ('ST', 'San Tomė ir Prinsipė', 'São Tomé & Príncipe', false),
  ('SV', 'Salvadoras', 'El Salvador', false),
  ('SX', 'Sint Martenas', 'Sint Maarten', false),
  ('SY', 'Sirija', 'Syria', false),
  ('SZ', 'Svazilandas', 'Eswatini', false),
  ('TC', 'Terkso ir Kaikoso Salos', 'Turks & Caicos Islands', false),
  ('TD', 'Čadas', 'Chad', false),
  ('TF', 'Prancūzijos Pietų sritys', 'French Southern Territories', false),
  ('TG', 'Togas', 'Togo', false),
  ('TH', 'Tailandas', 'Thailand', false),
  ('TJ', 'Tadžikija', 'Tajikistan', false),
  ('TK', 'Tokelau', 'Tokelau', false),
  ('TL', 'Rytų Timoras', 'Timor-Leste', false),
  ('TM', 'Turkmėnistanas', 'Turkmenistan', false),
  ('TN', 'Tunisas', 'Tunisia', false),
  ('TO', 'Tonga', 'Tonga', false),
  ('TR', 'Turkija', 'Türkiye', false),
  ('TT', 'Trinidadas ir Tobagas', 'Trinidad & Tobago', false),
  ('TV', 'Tuvalu', 'Tuvalu', false),
  ('TW', 'Taivanas', 'Taiwan', false),
  ('TZ', 'Tanzanija', 'Tanzania', false),
  ('UA', 'Ukraina', 'Ukraine', false),
  ('UG', 'Uganda', 'Uganda', false),
  ('UM', 'Jungtinių Valstijų Mažosios Tolimosios Salos', 'U.S. Outlying Islands', false),
  ('US', 'Jungtinės Valstijos', 'United States', false),
  ('UY', 'Urugvajus', 'Uruguay', false),
  ('UZ', 'Uzbekistanas', 'Uzbekistan', false),
  ('VA', 'Vatikano Miesto Valstybė', 'Vatican City', false),
  ('VC', 'Šventasis Vincentas ir Grenadinai', 'St. Vincent & Grenadines', false),
  ('VE', 'Venesuela', 'Venezuela', false),
  ('VG', 'Didžiosios Britanijos Mergelių Salos', 'British Virgin Islands', false),
  ('VI', 'Jungtinių Valstijų Mergelių Salos', 'U.S. Virgin Islands', false),
  ('VN', 'Vietnamas', 'Vietnam', false),
  ('VU', 'Vanuatu', 'Vanuatu', false),
  ('WF', 'Volisas ir Futūna', 'Wallis & Futuna', false),
  ('WS', 'Samoa', 'Samoa', false),
  ('YE', 'Jemenas', 'Yemen', false),
  ('YT', 'Majotas', 'Mayotte', false),
  ('ZA', 'Pietų Afrika', 'South Africa', false),
  ('ZM', 'Zambija', 'Zambia', false),
  ('ZW', 'Zimbabvė', 'Zimbabwe', false)
on conflict (code) do nothing;
