/**
 * Work Market Atlas — the 28 high-level work/market blocks (original
 * Labourmarket.ai taxonomy). This is the spine of the live market map +
 * marketplace: every demand, worker signal, offer, brigade and map layer maps
 * back to one of these blocks.
 *
 * Honest by construction:
 *   - `mapEligible` says whether a block can appear on the market map AS A
 *     SIGNAL (never a fake marker — coordinates come later via a verified path).
 *   - `needsDocuments` flags blocks where cross-border / regulated work needs a
 *     document / legal-eligibility path before it is shown as "ready abroad".
 *   - `rateSignalCapable` only marks blocks where a real rate signal can exist;
 *     it never invents averages.
 *
 * No external brand / product / job-board names anywhere (guard-enforced).
 * Pure data + helpers, no DB.
 */

import type { WorkMarketAction, WorkMarketIdentity } from "./actions";

export type WorkMarketSubcategory = {
  slug: string;
  labelLt: string;
  labelEn: string;
};

export type WorkMarketCategory = {
  /** Stable kebab-case id used in code / URLs / map layer keys. */
  slug: string;
  labelLt: string;
  labelEn: string;
  /** One human-clear sentence (LT) — what this block actually is. */
  descriptionLt: string;
  descriptionEn: string;
  /** 5–15 concrete subcategories. */
  subcategories: readonly WorkMarketSubcategory[];
  /** Related skill slugs (existing catalogue slugs where they exist; some are
   *  forward-looking for sectors the skill catalogue has not reached yet). */
  relatedSkills: readonly string[];
  /** Which market actions this block supports. */
  actions: readonly WorkMarketAction[];
  /** Which base identity can own this block. */
  identity: WorkMarketIdentity;
  /** Can it appear on the market map (as a SIGNAL)? */
  mapEligible: boolean;
  /** Does cross-border / regulated work here need a document / legal path? */
  needsDocuments: boolean;
  /** Can it be part of a brigade / team capacity? */
  brigadeCapable: boolean;
  /** Can it carry a real price / rate signal? */
  rateSignalCapable: boolean;
  /** One-line icon concept (full visual spec lives in visual-concepts.ts). */
  iconConcept: string;
};

/** Short helper to build a subcategory tersely. */
const s = (slug: string, lt: string, en: string): WorkMarketSubcategory => ({
  slug,
  labelLt: lt,
  labelEn: en,
});

export const WORK_MARKET_CATEGORIES: readonly WorkMarketCategory[] = [
  {
    slug: "construction-sites",
    labelLt: "Statyba ir objektai",
    labelEn: "Construction & sites",
    descriptionLt: "Pagrindiniai statybos darbai objekte — nuo pamatų iki konstrukcijų.",
    descriptionEn: "Core construction work on site — from foundations to structures.",
    subcategories: [
      s("groundworks", "Pamatai ir žemės paruošimas", "Foundations & ground prep"),
      s("masonry", "Mūro darbai", "Masonry"),
      s("concrete", "Betonavimas", "Concreting"),
      s("formwork", "Klojiniai", "Formwork"),
      s("rebar", "Armatūra", "Reinforcement"),
      s("general-site", "Bendrieji objekto darbai", "General site work"),
      s("demolition", "Griovimas ir demontažas", "Demolition"),
    ],
    relatedSkills: ["bricklaying", "concrete-pouring", "formwork", "rebar-cutting", "demolition", "general-labour"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "stacked-block-and-trowel silhouette",
  },
  {
    slug: "finishing-interior",
    labelLt: "Apdaila ir vidaus darbai",
    labelEn: "Finishing & interior",
    descriptionLt: "Vidaus apdaila — sienos, lubos, grindys, dažymas, plytelės.",
    descriptionEn: "Interior finishing — walls, ceilings, floors, painting, tiling.",
    subcategories: [
      s("plastering", "Tinkavimas", "Plastering"),
      s("skim-painting", "Glaistymas ir dažymas", "Skim & painting"),
      s("tiling", "Plytelės", "Tiling"),
      s("flooring", "Grindys", "Flooring"),
      s("drywall", "Gipskartonis ir pertvaros", "Drywall & partitions"),
      s("ceilings", "Lubų sistemos", "Ceiling systems"),
      s("decorative", "Dekoratyvinė apdaila", "Decorative finishes"),
    ],
    relatedSkills: ["plastering", "skim-coating", "painting", "tiling", "flooring", "drywall", "ceiling-systems"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "roller-and-tile-grid mark",
  },
  {
    slug: "engineering-systems",
    labelLt: "Inžinerinės sistemos",
    labelEn: "Engineering systems",
    descriptionLt: "Pastato inžinerinės sistemos ir jų montavimas.",
    descriptionEn: "Building engineering systems and their installation.",
    subcategories: [
      s("system-design", "Sistemų išdėstymas", "System layout"),
      s("pipework", "Vamzdynai", "Pipework"),
      s("ducting", "Ortakiai", "Ducting"),
      s("low-voltage", "Silpnosios srovės", "Low voltage"),
      s("commissioning", "Paleidimas ir derinimas", "Commissioning"),
      s("maintenance", "Priežiūra", "Maintenance"),
    ],
    relatedSkills: ["pipefitting", "low-voltage", "industrial-electric", "blueprint-reading"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "interlocking-pipes-and-circuit node",
  },
  {
    slug: "electrical-automation",
    labelLt: "Elektra ir automatika",
    labelEn: "Electrical & automation",
    descriptionLt: "Elektros instaliacija, apšvietimas, valdymas ir automatika.",
    descriptionEn: "Electrical installation, lighting, control and automation.",
    subcategories: [
      s("wiring", "Instaliacija", "Wiring"),
      s("lighting", "Apšvietimas", "Lighting"),
      s("cable-pulling", "Kabelių tiesimas", "Cable pulling"),
      s("testing", "Matavimai ir bandymai", "Testing & measurement"),
      s("industrial", "Pramoninė elektra", "Industrial electrical"),
      s("automation", "Automatika ir valdymas", "Automation & control"),
    ],
    relatedSkills: ["electrical-install", "lighting-install", "cable-pulling", "electrical-testing", "industrial-electric", "low-voltage"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "bolt-through-terminal mark",
  },
  {
    slug: "plumbing-heating",
    labelLt: "Santechnika ir šildymas",
    labelEn: "Plumbing & heating",
    descriptionLt: "Vandentiekis, nuotekos, šildymo sistemos ir prietaisai.",
    descriptionEn: "Water supply, drainage, heating systems and fixtures.",
    subcategories: [
      s("water-supply", "Vandentiekis", "Water supply"),
      s("drainage", "Nuotekos", "Drainage"),
      s("heating", "Šildymo sistemos", "Heating systems"),
      s("sanitary", "Santechnikos prietaisai", "Sanitary fixtures"),
      s("underfloor", "Grindinis šildymas", "Underfloor heating"),
      s("service", "Priežiūra ir remontas", "Service & repair"),
    ],
    relatedSkills: ["plumbing", "drainage", "heating-install", "sanitary-install", "pipefitting"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "pipe-bend-with-droplet mark",
  },
  {
    slug: "ventilation-climate",
    labelLt: "Ventiliacija ir kondicionavimas",
    labelEn: "Ventilation & climate",
    descriptionLt: "Vėdinimo, oro kondicionavimo ir klimato sistemos.",
    descriptionEn: "Ventilation, air-conditioning and climate systems.",
    subcategories: [
      s("ventilation", "Vėdinimas", "Ventilation"),
      s("ac", "Kondicionavimas", "Air conditioning"),
      s("ducting", "Ortakių montavimas", "Duct installation"),
      s("recovery", "Rekuperacija", "Heat recovery"),
      s("balancing", "Sistemų balansavimas", "System balancing"),
      s("service", "Aptarnavimas", "Servicing"),
    ],
    relatedSkills: ["ventilation", "hvac-install"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "fan-blade-in-airflow mark",
  },
  {
    slug: "roofs-facades",
    labelLt: "Stogai ir fasadai",
    labelEn: "Roofs & facades",
    descriptionLt: "Stogų dengimas, fasadų įrengimas ir apšiltinimas.",
    descriptionEn: "Roofing, facade installation and insulation.",
    subcategories: [
      s("pitched-roof", "Šlaitiniai stogai", "Pitched roofs"),
      s("flat-roof", "Plokšti stogai", "Flat roofs"),
      s("gutters", "Lietvamzdžiai", "Gutters"),
      s("facade", "Fasadų apdaila", "Facade finishing"),
      s("facade-insulation", "Fasadų šiltinimas", "Facade insulation"),
      s("waterproofing", "Hidroizoliacija", "Waterproofing"),
    ],
    relatedSkills: ["roofing", "flat-roofing", "roof-tiling", "roof-insulation", "gutter-install", "facade-plaster", "waterproofing"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "roof-ridge-over-wall mark",
  },
  {
    slug: "wood-carpentry",
    labelLt: "Mediena, staliai, montavimas",
    labelEn: "Wood, carpentry, fit-out",
    descriptionLt: "Medienos darbai, staliaus gaminiai, baldų ir konstrukcijų montavimas.",
    descriptionEn: "Woodwork, joinery, furniture and structure fit-out.",
    subcategories: [
      s("framing", "Karkasai ir konstrukcijos", "Framing & structures"),
      s("joinery", "Staliaus gaminiai", "Joinery"),
      s("doors-windows", "Durys ir langai", "Doors & windows"),
      s("furniture-fit", "Baldų montavimas", "Furniture fitting"),
      s("decking", "Terasos ir apdaila", "Decking & trim"),
      s("repair", "Remontas", "Repair"),
    ],
    relatedSkills: ["carpentry", "timber-framing", "joinery", "door-window-install", "furniture-fitting"],
    actions: ["work", "hire", "buy", "sell", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "plank-and-chisel mark",
  },
  {
    slug: "metal-welding",
    labelLt: "Metalas, suvirinimas, konstrukcijos",
    labelEn: "Metal, welding, structures",
    descriptionLt: "Metalo apdirbimas, suvirinimas ir plieno konstrukcijos.",
    descriptionEn: "Metalwork, welding and steel structures.",
    subcategories: [
      s("structural-steel", "Plieno konstrukcijos", "Structural steel"),
      s("welding", "Suvirinimas", "Welding"),
      s("cutting", "Pjovimas", "Cutting"),
      s("fabrication", "Gamyba ir surinkimas", "Fabrication"),
      s("rigging", "Kėlimas ir tvirtinimas", "Rigging"),
      s("repair", "Remontas", "Repair"),
    ],
    relatedSkills: ["structural-steel", "mig-mag-welding", "tig-welding", "arc-welding", "gas-cutting", "steel-fixing", "rigging"],
    actions: ["work", "hire", "buy", "sell", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "weld-arc-on-beam mark",
  },
  {
    slug: "roads-earthworks",
    labelLt: "Keliai, žemės darbai, infrastruktūra",
    labelEn: "Roads, earthworks, infrastructure",
    descriptionLt: "Žemės kasimas, kelių tiesimas ir inžinerinė infrastruktūra.",
    descriptionEn: "Earthmoving, road building and civil infrastructure.",
    subcategories: [
      s("excavation", "Kasimas", "Excavation"),
      s("road-base", "Kelio pagrindai", "Road base"),
      s("paving", "Dangos", "Paving"),
      s("utilities", "Inžineriniai tinklai", "Utility trenches"),
      s("compaction", "Tankinimas", "Compaction"),
      s("machinery", "Technikos darbai", "Machinery work"),
    ],
    relatedSkills: ["earthworks", "excavator-operator", "bulldozer-operator", "grader-operator", "compactor-operator", "loader-operator"],
    actions: ["work", "hire", "rent", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "excavator-bucket-over-trench mark",
  },
  {
    slug: "warehouse-logistics",
    labelLt: "Sandėliai, logistika, vairavimas",
    labelEn: "Warehouse, logistics, driving",
    descriptionLt: "Sandėlio darbai, krovinių tvarkymas ir vidaus transportas.",
    descriptionEn: "Warehouse work, goods handling and internal transport.",
    subcategories: [
      s("picking", "Komplektavimas", "Order picking"),
      s("forklift", "Krautuvai", "Forklift work"),
      s("loading", "Pakrovimas ir iškrovimas", "Loading & unloading"),
      s("inventory", "Atsargų tvarkymas", "Inventory"),
      s("dispatch", "Išsiuntimas", "Dispatch"),
      s("driving", "Vidaus vairavimas", "Internal driving"),
    ],
    relatedSkills: ["forklift-operator", "manual-handling", "material-transport", "materials-management"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "pallet-and-arrow mark",
  },
  {
    slug: "manufacturing-factory",
    labelLt: "Gamyba ir fabrikai",
    labelEn: "Manufacturing & factories",
    descriptionLt: "Gamybos linijų, surinkimo ir fabrikų darbai.",
    descriptionEn: "Production line, assembly and factory work.",
    subcategories: [
      s("assembly", "Surinkimas", "Assembly"),
      s("machine-operation", "Staklių operavimas", "Machine operation"),
      s("packaging", "Pakavimas", "Packaging"),
      s("quality", "Kokybės kontrolė", "Quality control"),
      s("line-support", "Linijos aptarnavimas", "Line support"),
      s("maintenance", "Įrangos priežiūra", "Equipment maintenance"),
    ],
    relatedSkills: ["quality-control", "manual-handling", "materials-management"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "gear-on-conveyor mark",
  },
  {
    slug: "agriculture-seasonal",
    labelLt: "Žemės ūkis ir sezoniniai darbai",
    labelEn: "Agriculture & seasonal",
    descriptionLt: "Lauko, šiltnamių, derliaus ir sezoniniai ūkio darbai.",
    descriptionEn: "Field, greenhouse, harvest and seasonal farm work.",
    subcategories: [
      s("harvest", "Derliaus nuėmimas", "Harvesting"),
      s("greenhouse", "Šiltnamiai", "Greenhouses"),
      s("planting", "Sodinimas ir priežiūra", "Planting & tending"),
      s("sorting", "Rūšiavimas ir pakavimas", "Sorting & packing"),
      s("livestock", "Gyvulininkystė", "Livestock"),
      s("machinery", "Ūkio technika", "Farm machinery"),
    ],
    relatedSkills: ["manual-handling"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "leaf-and-basket mark",
  },
  {
    slug: "food-kitchen",
    labelLt: "Maistas, virtuvė, restoranai",
    labelEn: "Food, kitchen, restaurants",
    descriptionLt: "Virtuvės, maisto ruošimo ir aptarnavimo darbai.",
    descriptionEn: "Kitchen, food preparation and service work.",
    subcategories: [
      s("kitchen", "Virtuvės darbas", "Kitchen work"),
      s("prep", "Maisto ruošimas", "Food prep"),
      s("dishwashing", "Indų plovimas", "Dishwashing"),
      s("service", "Aptarnavimas", "Table service"),
      s("barista", "Baras ir kava", "Bar & coffee"),
      s("catering", "Išvežiojamas maitinimas", "Catering"),
    ],
    relatedSkills: [],
    actions: ["work", "hire", "buy", "sell", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "knife-and-flame mark",
  },
  {
    slug: "cleaning-maintenance",
    labelLt: "Valymas ir priežiūra",
    labelEn: "Cleaning & maintenance",
    descriptionLt: "Patalpų, objektų ir teritorijų valymas bei priežiūra.",
    descriptionEn: "Cleaning and upkeep of premises, sites and grounds.",
    subcategories: [
      s("post-build", "Statybinis valymas", "Post-construction cleaning"),
      s("commercial", "Komercinių patalpų valymas", "Commercial cleaning"),
      s("residential", "Būstų valymas", "Residential cleaning"),
      s("grounds", "Teritorijų priežiūra", "Grounds upkeep"),
      s("window", "Langų valymas", "Window cleaning"),
      s("waste", "Atliekų tvarkymas", "Waste handling"),
    ],
    relatedSkills: ["site-cleaning"],
    actions: ["work", "hire", "buy", "sell", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: false,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "brush-with-sparkle mark",
  },
  {
    slug: "hospitality-accommodation",
    labelLt: "Viešbučiai ir apgyvendinimas",
    labelEn: "Hotels & hospitality",
    descriptionLt: "Apgyvendinimo įstaigų aptarnavimo ir priežiūros darbai.",
    descriptionEn: "Service and upkeep roles in accommodation venues.",
    subcategories: [
      s("housekeeping", "Kambarinės", "Housekeeping"),
      s("reception", "Registratūra", "Reception"),
      s("maintenance", "Techninė priežiūra", "Maintenance"),
      s("breakfast", "Pusryčiai ir aptarnavimas", "Breakfast & service"),
      s("laundry", "Skalbykla", "Laundry"),
      s("events", "Renginiai", "Events"),
    ],
    relatedSkills: [],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "bell-and-key mark",
  },
  {
    slug: "care-people",
    labelLt: "Slauga ir pagalba žmonėms",
    labelEn: "Care & support for people",
    descriptionLt: "Priežiūros, slaugos ir pagalbos žmonėms paslaugos.",
    descriptionEn: "Care, nursing-support and personal-help services.",
    subcategories: [
      s("elderly", "Pagyvenusių priežiūra", "Elderly care"),
      s("home-help", "Pagalba namuose", "Home help"),
      s("childcare", "Vaikų priežiūra", "Childcare"),
      s("disability", "Pagalba neįgaliesiems", "Disability support"),
      s("companion", "Palydėjimas ir bendravimas", "Companionship"),
    ],
    relatedSkills: [],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "open-hand-supporting-figure mark",
  },
  {
    slug: "security-facility",
    labelLt: "Apsauga ir objektų priežiūra",
    labelEn: "Security & facility watch",
    descriptionLt: "Objektų apsaugos ir budėjimo darbai.",
    descriptionEn: "Site security and watch duties.",
    subcategories: [
      s("site-watch", "Objektų sauga", "Site watch"),
      s("access", "Praėjimo kontrolė", "Access control"),
      s("patrol", "Patruliavimas", "Patrol"),
      s("event-security", "Renginių apsauga", "Event security"),
      s("monitoring", "Stebėjimas", "Monitoring"),
    ],
    relatedSkills: [],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "shield-and-eye mark",
  },
  {
    slug: "tools-equipment-rental",
    labelLt: "Įrankiai, technika ir įrangos nuoma",
    labelEn: "Tools, machinery & equipment rental",
    descriptionLt: "Įrankių, technikos ir įrangos nuoma bei pardavimas.",
    descriptionEn: "Renting and selling tools, machinery and equipment.",
    subcategories: [
      s("hand-tools", "Rankiniai įrankiai", "Hand tools"),
      s("power-tools", "Elektriniai įrankiai", "Power tools"),
      s("machinery", "Statybinė technika", "Construction machinery"),
      s("access", "Pastoliai ir keltuvai", "Scaffolding & lifts"),
      s("attachments", "Padargai ir priedai", "Attachments"),
      s("transport", "Pristatymas", "Delivery"),
    ],
    relatedSkills: ["hand-tools"],
    actions: ["rent", "buy", "sell", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: false,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "wrench-and-tag mark",
  },
  {
    slug: "transport-rides",
    labelLt: "Transportas ir pavežėjimas",
    labelEn: "Transport & rides",
    descriptionLt: "Žmonių ir krovinių pervežimo bei pavežėjimo paslaugos.",
    descriptionEn: "Moving people and goods, and ride-sharing.",
    subcategories: [
      s("crew-rides", "Brigadų pavežėjimas", "Crew rides"),
      s("goods", "Krovinių pervežimas", "Goods transport"),
      s("relocation", "Perkraustymas", "Relocation"),
      s("airport", "Oro uosto reisai", "Airport runs"),
      s("delivery", "Pristatymas", "Delivery"),
    ],
    relatedSkills: [],
    actions: ["buy", "sell", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "van-with-route-line mark",
  },
  {
    slug: "local-paperwork-help",
    labelLt: "Vertimas, dokumentai, vietinė pagalba",
    labelEn: "Translation, paperwork, local help",
    descriptionLt: "Vertimo, dokumentų tvarkymo ir vietinės pagalbos paslaugos.",
    descriptionEn: "Translation, document handling and local-help services.",
    subcategories: [
      s("translation", "Vertimas", "Translation"),
      s("documents", "Dokumentų tvarkymas", "Document handling"),
      s("registration", "Registracijos", "Registrations"),
      s("interpreting", "Vertėjavimas vietoje", "On-site interpreting"),
      s("orientation", "Įsikūrimo pagalba", "Settling-in help"),
    ],
    relatedSkills: [],
    actions: ["buy", "sell", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: false,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "speech-bubbles-and-stamp mark",
  },
  {
    slug: "accommodation-offers",
    labelLt: "Apgyvendinimo pasiūlymai",
    labelEn: "Accommodation offers",
    descriptionLt: "Kambariai, butai ir laikinos vietos komandoms bei darbuotojams.",
    descriptionEn: "Rooms, flats and temporary places for teams and workers.",
    subcategories: [
      s("rooms", "Kambariai", "Rooms"),
      s("flats", "Butai", "Flats"),
      s("crew-housing", "Būstas brigadoms", "Crew housing"),
      s("short-term", "Trumpalaikis būstas", "Short-term stays"),
      s("shared", "Bendras būstas", "Shared housing"),
    ],
    relatedSkills: [],
    actions: ["rent", "buy", "sell", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: false,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "bed-inside-roof mark",
  },
  {
    slug: "brigade-capacity",
    labelLt: "Brigados / komandos pajėgumas",
    labelEn: "Brigade / team capacity",
    descriptionLt: "Paruoštos brigados ir komandos su laisvu pajėgumu darbams.",
    descriptionEn: "Ready brigades and teams with free capacity for work.",
    subcategories: [
      s("finishing-crew", "Apdailos brigada", "Finishing crew"),
      s("concrete-crew", "Betonavimo brigada", "Concrete crew"),
      s("roofing-crew", "Stogdengių brigada", "Roofing crew"),
      s("mep-crew", "Inžinerinių sistemų brigada", "MEP crew"),
      s("general-crew", "Universali brigada", "General crew"),
    ],
    relatedSkills: ["team-coordination", "work-scheduling"],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: true,
    brigadeCapable: true,
    rateSignalCapable: true,
    iconConcept: "three-figures-in-formation mark",
  },
  {
    slug: "small-local-services",
    labelLt: "Smulkios vietinės paslaugos",
    labelEn: "Small local services",
    descriptionLt: "Smulkūs vietiniai darbai ir rankų darbo prekės.",
    descriptionEn: "Small local jobs and handmade goods.",
    subcategories: [
      s("handywork", "Smulkus remontas", "Handywork"),
      s("handmade", "Rankų darbo prekės", "Handmade goods"),
      s("garden", "Sodo darbai", "Garden work"),
      s("moving-help", "Pagalba kraustantis", "Moving help"),
      s("errands", "Pavedimai", "Errands"),
    ],
    relatedSkills: [],
    actions: ["work", "buy", "sell", "seek_help"],
    identity: "person",
    mapEligible: true,
    needsDocuments: false,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "hand-and-small-gear mark",
  },
  {
    slug: "urgent-action-radar",
    labelLt: "Skubūs darbai / action radar",
    labelEn: "Urgent jobs / action radar",
    descriptionLt: "Skubūs poreikiai, kuriuos verta sutvarkyti dabar.",
    descriptionEn: "Urgent needs worth acting on right now.",
    subcategories: [
      s("urgent-demand", "Skubus poreikis", "Urgent demand"),
      s("same-week", "Tos savaitės darbai", "Same-week jobs"),
      s("replacement", "Pakeitimas skubiai", "Urgent replacement"),
      s("gap-cover", "Spragos užpildymas", "Gap cover"),
    ],
    relatedSkills: [],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: false,
    brigadeCapable: true,
    rateSignalCapable: false,
    iconConcept: "pulse-ring-radar mark",
  },
  {
    slug: "rate-map",
    labelLt: "Rinkos kainos / rate map",
    labelEn: "Market rates / rate map",
    descriptionLt: "Realūs kainų ir atlygio signalai pagal sritį ir vietą.",
    descriptionEn: "Real price and pay signals by field and location.",
    subcategories: [
      s("worker-pay", "Darbuotojo atlygis", "Worker pay"),
      s("company-cost", "Įmonės kaina", "Company cost"),
      s("freelance-rate", "Individualus įkainis", "Freelance rate"),
      s("brigade-rate", "Brigados įkainis", "Brigade rate"),
      s("service-price", "Paslaugos kaina", "Service price"),
    ],
    relatedSkills: [],
    actions: ["buy", "sell"],
    identity: "both",
    mapEligible: true,
    needsDocuments: false,
    brigadeCapable: false,
    rateSignalCapable: true,
    iconConcept: "coin-stack-over-map-pin mark",
  },
  {
    slug: "opportunity-gaps",
    labelLt: "Galimybių spragos / opportunity gaps",
    labelEn: "Opportunity gaps",
    descriptionLt: "Vietos, kur yra paklausa be pasiūlos ar atvirkščiai.",
    descriptionEn: "Places where demand lacks supply or the reverse.",
    subcategories: [
      s("demand-no-supply", "Poreikis be žmonių", "Demand without workers"),
      s("supply-no-demand", "Žmonės be projektų", "Workers without projects"),
      s("no-accommodation", "Trūksta apgyvendinimo", "No accommodation"),
      s("no-transport", "Trūksta transporto", "No transport"),
      s("no-documents", "Trūksta dokumentų kelio", "No document path"),
    ],
    relatedSkills: [],
    actions: ["work", "hire", "seek_help"],
    identity: "both",
    mapEligible: true,
    needsDocuments: false,
    brigadeCapable: false,
    rateSignalCapable: false,
    iconConcept: "dashed-outline-gap mark",
  },
  {
    slug: "moderation-review",
    labelLt: "Moderatoriams skirta marketplace peržiūra",
    labelEn: "Marketplace moderation review",
    descriptionLt: "Moderatorių darbo sritis — pasiūlymų peržiūra ir patikimumas.",
    descriptionEn: "Moderator workspace — reviewing offers and trust.",
    subcategories: [
      s("pending", "Laukia peržiūros", "Pending review"),
      s("reported", "Pranešta", "Reported"),
      s("verify-location", "Vietos patikra", "Location check"),
      s("verify-identity", "Tapatybės patikra", "Identity check"),
      s("hidden", "Paslėpti", "Hidden"),
    ],
    relatedSkills: [],
    actions: ["seek_help"],
    identity: "company",
    mapEligible: false,
    needsDocuments: false,
    brigadeCapable: false,
    rateSignalCapable: false,
    iconConcept: "checklist-with-magnifier mark",
  },
];
