import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const REPO = resolve(__dirname, "../../../..");
const json = (p: string) => JSON.parse(readFileSync(resolve(REPO, p), "utf8"));

const appConfig = json("apps/mobile/app.json").expo;
const eas = json("apps/mobile/eas.json");
const mobilePkg = json("apps/mobile/package.json");

/**
 * WHAT THIS PROTECTS — the store-release configuration of the native client.
 *
 * `apps/mobile/android` and `apps/mobile/ios` are GITIGNORED: the native
 * projects are generated by `expo prebuild` from `app.json` on every build and
 * are never hand-maintained. That makes `app.json` the ONLY place a store
 * requirement can be stated, and the only place it can silently regress — no
 * reviewer sees the generated plist or manifest in a diff.
 *
 * Three of the pins below exist because the DEFAULT was wrong rather than
 * missing, which is the harder failure to notice:
 *
 * · Apple's privacy manifest. Expo's template emits
 *   `NSPrivacyCollectedDataTypes` as an EMPTY ARRAY — an assertion to Apple
 *   that this product collects nothing about a person. It collects an
 *   account, a name, a user id and the work journal's own content. An empty
 *   list there is not an omission, it is a false declaration, so the list is
 *   pinned non-empty and every entry pinned to `Tracking: false` +
 *   app-functionality (the app carries no analytics or advertising SDK — see
 *   the dependency pin below, which is what makes that claim checkable).
 * · The legacy Android storage permissions. `READ_/WRITE_EXTERNAL_STORAGE`
 *   arrive from the React Native template and Google Play makes an app that
 *   requests them answer for them. This client opens no file, no picker and
 *   no download — verified: nothing under `apps/mobile` imports a file-system
 *   or media module — so they are BLOCKED, and asking for a permission the
 *   product does not use is the kind of claim this repository does not make.
 * · `versionCode` / `buildNumber`. Both stores REFUSE an upload without them
 *   and Expo defaults them to 1 silently, so the first release would be fine
 *   and the second would be rejected at the worst moment.
 *
 * NOT PINNED HERE, deliberately: signing, store credentials, an Expo project
 * id, and the completeness of the collected-data list for legal sign-off.
 * Those are owner gates and no agent may settle them — see
 * `docs/mobile/STORE_RELEASE_READINESS_2026-09-13.md`.
 */
describe("mobile store-release config — the generated native project is only as honest as app.json", () => {
  it("both stores can accept a build: an id and a version per platform", () => {
    expect(appConfig.ios.bundleIdentifier).toBe("ai.labourmarket.app");
    expect(appConfig.android.package).toBe("ai.labourmarket.app");
    expect(typeof appConfig.android.versionCode).toBe("number");
    expect(appConfig.android.versionCode).toBeGreaterThanOrEqual(1);
    expect(typeof appConfig.ios.buildNumber).toBe("string");
    expect(appConfig.ios.buildNumber.length).toBeGreaterThan(0);
  });

  it("the deep-link scheme matches the one the auth guard is built on", () => {
    // `labourmarketai://` is the intent filter on the single-task activity and
    // the expo-router auth guard. A renamed scheme breaks the sign-in return
    // path on a real device, where nothing in CI would catch it.
    expect(appConfig.scheme).toBe("labourmarketai");
  });

  it("the privacy manifest declares what the product actually collects", () => {
    const pm = appConfig.ios.privacyManifests;
    const collected = pm.NSPrivacyCollectedDataTypes;
    expect(Array.isArray(collected)).toBe(true);
    // Codex P2 on #1732, and correct: a `length > 0` check would still pass
    // after an edit removed EmailAddress and left one entry standing — which
    // is the very false declaration this pin exists to prevent. Each type is
    // named, because each answers for something the client demonstrably
    // handles: the account it signs in with, the name and user id on the
    // profile it reads, and the journal content it writes.
    const declared = new Set(
      collected.map((t: Record<string, unknown>) => t.NSPrivacyCollectedDataType as string),
    );
    for (const required of [
      "NSPrivacyCollectedDataTypeEmailAddress",
      "NSPrivacyCollectedDataTypeName",
      "NSPrivacyCollectedDataTypeUserID",
      "NSPrivacyCollectedDataTypeOtherUserContent",
    ]) {
      expect(
        declared.has(required),
        `${required} is not declared. Removing a type the client handles is a false statement to Apple, not a smaller one.`,
      ).toBe(true);
    }
    for (const entry of collected) {
      expect(entry.NSPrivacyCollectedDataTypeTracking).toBe(false);
      expect(entry.NSPrivacyCollectedDataTypePurposes).toContain(
        "NSPrivacyCollectedDataTypePurposeAppFunctionality",
      );
    }
    expect(pm.NSPrivacyTracking).toBe(false);
    expect(pm.NSPrivacyTrackingDomains).toEqual([]);
  });

  it("every required-reason API the runtime uses carries a reason code", () => {
    const types = appConfig.ios.privacyManifests.NSPrivacyAccessedAPITypes;
    const byType = new Map<string, readonly string[]>(
      types.map((t: Record<string, unknown>) => [
        t.NSPrivacyAccessedAPIType as string,
        t.NSPrivacyAccessedAPITypeReasons as readonly string[],
      ]),
    );
    // The four React Native / Expo runtime touches. Apple rejects a build that
    // uses one of these without a reason, and the rejection names the API.
    for (const api of [
      "NSPrivacyAccessedAPICategoryUserDefaults",
      "NSPrivacyAccessedAPICategoryFileTimestamp",
      "NSPrivacyAccessedAPICategorySystemBootTime",
      "NSPrivacyAccessedAPICategoryDiskSpace",
    ]) {
      expect(byType.get(api)?.length ?? 0, `${api} carries no reason code`).toBeGreaterThan(0);
    }
  });

  it("blocks the legacy storage permissions the product does not use", () => {
    expect(appConfig.android.blockedPermissions).toEqual(
      expect.arrayContaining([
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
      ]),
    );
  });

  it("carries no analytics or advertising dependency — which is what makes NSPrivacyTracking: false true", () => {
    const deps = Object.keys(mobilePkg.dependencies ?? {});
    for (const dep of deps) {
      expect(
        /analytics|firebase|amplitude|segment|mixpanel|sentry|admob|facebook|appsflyer|adjust/i.test(dep),
        `${dep} is a tracking/analytics SDK — the privacy manifest's tracking declaration must be revisited before it ships.`,
      ).toBe(false);
    }
  });

  it("the build profiles hold no credential, key or account id", () => {
    const raw = JSON.stringify(eas);
    expect(raw).not.toMatch(/serviceAccount|ascAppId|appleId|appleTeamId|keystore|password|secret|token|-----BEGIN/i);
    for (const profile of ["development", "preview", "production"]) {
      expect(eas.build[profile], `eas.json has no ${profile} profile`).toBeDefined();
    }
    // Play takes an app bundle, not an APK. Getting this wrong is found at
    // upload time, after a build that takes half an hour.
    expect(eas.build.production.android.buildType).toBe("app-bundle");
  });

  it("the README does not claim a capability the code has already wired", () => {
    // THE EXPENSIVE ONE. `apps/mobile/README.md` said "What is NOT wired yet:
    // writes (journal draft→confirm)" for days after #1648 shipped
    // `JournalComposer`. On 2026-09-13 that sentence was copied into a new
    // release document and into a plan to BUILD the write path — the exact
    // duplicate-capability failure the product truth bootstrap exists to stop.
    // Nobody noticed, because a README is prose and prose is not checked.
    //
    // So the claim is checked against the code that decides it. This asserts
    // only the direction that misleads: the README may not say writes are
    // missing while the composer calls both halves of the write.
    const composer = readFileSync(
      resolve(REPO, "apps/mobile/src/screens/journal-composer.tsx"),
      "utf8",
    );
    const writesAreWired =
      composer.includes("journal.create_draft") && composer.includes("journal.confirm");
    expect(writesAreWired, "the composer no longer calls both halves of the write — re-read this guard's premise before changing it").toBe(true);
    const readme = readFileSync(resolve(REPO, "apps/mobile/README.md"), "utf8");
    expect(
      /NOT wired yet:[^.]*writes/i.test(readme),
      "apps/mobile/README.md says journal writes are not wired, and JournalComposer calls journal.create_draft and journal.confirm. Correct the README — a document that says a built capability is missing is how it gets built twice.",
    ).toBe(false);
  });

  it("the native projects stay generated, never committed", () => {
    const ignore = readFileSync(resolve(REPO, "apps/mobile/.gitignore"), "utf8");
    expect(ignore).toMatch(/^\/android$/m);
    expect(ignore).toMatch(/^\/ios$/m);
  });

  /**
   * DEEP LINKS — both halves, or neither.
   *
   * A universal/app link works only when the APP claims the domain and the
   * DOMAIN claims the app. The app's half is here in `app.json`; the domain's
   * half is `/.well-known/apple-app-site-association` and
   * `/.well-known/assetlinks.json`, which answer 404 until the owner sets the
   * Team ID and the signing fingerprints.
   *
   * That asymmetry is deliberate and safe (a link simply opens in the browser
   * meanwhile). What is NOT safe is deleting one half: an app that claims a
   * domain no longer served, or routes served for an app that no longer
   * claims them, both look configured and neither works.
   */
  it("the app claims the product domain on both platforms", () => {
    expect(appConfig.ios.associatedDomains).toContain("applinks:labourmarket.ai");
    const hosts = (appConfig.android.intentFilters ?? [])
      .flatMap((f: { data?: { host?: string }[] }) => f.data ?? [])
      .map((d: { host?: string }) => d.host);
    expect(hosts).toContain("labourmarket.ai");
  });

  it("the Android link filter asks to be verified, over https only", () => {
    // Without `autoVerify` Android shows a disambiguation dialog instead of
    // opening the app — the link "works" and the app never opens. And a
    // `http` scheme here would claim links this product does not serve.
    const filters = (appConfig.android.intentFilters ?? []) as {
      autoVerify?: boolean;
      data?: { scheme?: string }[];
    }[];
    expect(filters.length).toBeGreaterThan(0);
    for (const f of filters) {
      expect(f.autoVerify).toBe(true);
      for (const d of f.data ?? []) expect(d.scheme).toBe("https");
    }
  });

  it("the domain half exists as routes, so the owner sets a value and nothing else", () => {
    for (const p of [
      "apps/web/app/.well-known/apple-app-site-association/route.ts",
      "apps/web/app/.well-known/assetlinks.json/route.ts",
    ]) {
      expect(existsSync(resolve(REPO, p)), `${p} is missing — the app claims a domain that serves nothing`).toBe(true);
    }
  });
});
