import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const REPO = resolve(__dirname, "../../../..");
const json = (p: string) => JSON.parse(readFileSync(resolve(REPO, p), "utf8"));

const appConfig = json("apps/mobile/app.json").expo;
const eas = json("apps/mobile/eas.json");
const mobilePkg = json("apps/mobile/package.json");

/**
 * WHAT THIS PROTECTS — the store-release configuration of the native client.
 *
 * `apps/mobile/android` and `apps/mobile/ios` are GITIGNORED: the native
 * projects are generated by `expo prebuild` from `app.json` on every build and
 * are never hand-maintained. That makes `app.json` the ONLY place a store
 * requirement can be stated, and the only place it can silently regress — no
 * reviewer sees the generated plist or manifest in a diff.
 *
 * Three of the pins below exist because the DEFAULT was wrong rather than
 * missing, which is the harder failure to notice:
 *
 * · Apple's privacy manifest. Expo's template emits
 *   `NSPrivacyCollectedDataTypes` as an EMPTY ARRAY — an assertion to Apple
 *   that this product collects nothing about a person. It collects an
 *   account, a name, a user id and the work journal's own content. An empty
 *   list there is not an omission, it is a false declaration, so the list is
 *   pinned non-empty and every entry pinned to `Tracking: false` +
 *   app-functionality (the app carries no analytics or advertising SDK — see
 *   the dependency pin below, which is what makes that claim checkable).
 * · The legacy Android storage permissions. `READ_/WRITE_EXTERNAL_STORAGE`
 *   arrive from the React Native template and Google Play makes an app that
 *   requests them answer for them. This client opens no file, no picker and
 *   no download — verified: nothing under `apps/mobile` imports a file-system
 *   or media module — so they are BLOCKED, and asking for a permission the
 *   product does not use is the kind of claim this repository does not make.
 * · `versionCode` / `buildNumber`. Both stores REFUSE an upload without them
 *   and Expo defaults them to 1 silently, so the first release would be fine
 *   and the second would be rejected at the worst moment.
 *
 * NOT PINNED HERE, deliberately: signing, store credentials, an Expo project
 * id, and the completeness of the collected-data list for legal sign-off.
 * Those are owner gates and no agent may settle them — see
 * `docs/mobile/STORE_RELEASE_READINESS_2026-09-13.md`.
 */
describe("mobile store-release config — the generated native project is only as honest as app.json", () => {
  it("both stores can accept a build: an id and a version per platform", () => {
    expect(appConfig.ios.bundleIdentifier).toBe("ai.labourmarket.app");
    expect(appConfig.android.package).toBe("ai.labourmarket.app");
    expect(typeof appConfig.android.versionCode).toBe("number");
    expect(appConfig.android.versionCode).toBeGreaterThanOrEqual(1);
    expect(typeof appConfig.ios.buildNumber).toBe("string");
    expect(appConfig.ios.buildNumber.length).toBeGreaterThan(0);
  });

  it("the deep-link scheme matches the one the auth guard is built on", () => {
    // `labourmarketai://` is the intent filter on the single-task activity and
    // the expo-router auth guard. A renamed scheme breaks the sign-in return
    // path on a real device, where nothing in CI would catch it.
    expect(appConfig.scheme).toBe("labourmarketai");
  });

  it("the privacy manifest declares what the product actually collects", () => {
    const pm = appConfig.ios.privacyManifests;
    const collected = pm.NSPrivacyCollectedDataTypes;
    expect(Array.isArray(collected)).toBe(true);
    expect(
      collected.length,
      "An empty NSPrivacyCollectedDataTypes tells Apple this product collects nothing about a person. It collects an account, a name, a user id and the journal's content.",
    ).toBeGreaterThan(0);
    for (const entry of collected) {
      expect(entry.NSPrivacyCollectedDataTypeTracking).toBe(false);
      expect(entry.NSPrivacyCollectedDataTypePurposes).toContain(
        "NSPrivacyCollectedDataTypePurposeAppFunctionality",
      );
    }
    expect(pm.NSPrivacyTracking).toBe(false);
    expect(pm.NSPrivacyTrackingDomains).toEqual([]);
  });

  it("every required-reason API the runtime uses carries a reason code", () => {
    const types = appConfig.ios.privacyManifests.NSPrivacyAccessedAPITypes;
    const byType = new Map<string, readonly string[]>(
      types.map((t: Record<string, unknown>) => [
        t.NSPrivacyAccessedAPIType as string,
        t.NSPrivacyAccessedAPITypeReasons as readonly string[],
      ]),
    );
    // The four React Native / Expo runtime touches. Apple rejects a build that
    // uses one of these without a reason, and the rejection names the API.
    for (const api of [
      "NSPrivacyAccessedAPICategoryUserDefaults",
      "NSPrivacyAccessedAPICategoryFileTimestamp",
      "NSPrivacyAccessedAPICategorySystemBootTime",
      "NSPrivacyAccessedAPICategoryDiskSpace",
    ]) {
      expect(byType.get(api)?.length ?? 0, `${api} carries no reason code`).toBeGreaterThan(0);
    }
  });

  it("blocks the legacy storage permissions the product does not use", () => {
    expect(appConfig.android.blockedPermissions).toEqual(
      expect.arrayContaining([
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
      ]),
    );
  });

  it("carries no analytics or advertising dependency — which is what makes NSPrivacyTracking: false true", () => {
    const deps = Object.keys(mobilePkg.dependencies ?? {});
    for (const dep of deps) {
      expect(
        /analytics|firebase|amplitude|segment|mixpanel|sentry|admob|facebook|appsflyer|adjust/i.test(dep),
        `${dep} is a tracking/analytics SDK — the privacy manifest's tracking declaration must be revisited before it ships.`,
      ).toBe(false);
    }
  });

  it("the build profiles hold no credential, key or account id", () => {
    const raw = JSON.stringify(eas);
    expect(raw).not.toMatch(/serviceAccount|ascAppId|appleId|appleTeamId|keystore|password|secret|token|-----BEGIN/i);
    for (const profile of ["development", "preview", "production"]) {
      expect(eas.build[profile], `eas.json has no ${profile} profile`).toBeDefined();
    }
    // Play takes an app bundle, not an APK. Getting this wrong is found at
    // upload time, after a build that takes half an hour.
    expect(eas.build.production.android.buildType).toBe("app-bundle");
  });

  it("the native projects stay generated, never committed", () => {
    const ignore = readFileSync(resolve(REPO, "apps/mobile/.gitignore"), "utf8");
    expect(ignore).toMatch(/^\/android$/m);
    expect(ignore).toMatch(/^\/ios$/m);
  });
});
